version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: test.php
    tty: true
    networks:
      - docker.network
    volumes:
      - "~/test:/var/www"

  nginx:
    build: ./docker/nginx
    container_name: test.nginx
    restart: unless-stopped
    ports:
      - "8085:80" 
    tty: true
    depends_on:
      - php
    networks:
      - docker.network
    volumes:
      - "./nginx/log:/var/log/nginx"
      - "~/test:/var/www"

networks:
  docker.network:
    driver: bridge

